// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCzszmSA7nOID-OZgDi7tKcAGQJxXVVz_c",
      authDomain: "tsuyosuketest.firebaseapp.com",
      projectId: "tsuyosuketest",
      storageBucket: "tsuyosuketest.appspot.com",
      messagingSenderId: "923210326457",
      appId: "1:923210326457:web:a366a0de3867629ff51668",
      measurementId: "G-ZGPP5KWBXD"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCf7Ux-CFqX8OBhO70Sh0GF4fPBVzUIFY',
    appId: '1:765408552100:android:01c191c73dacc075e8b231',
    messagingSenderId: '765408552100',
    projectId: 'tsuyosuketeniss',
    databaseURL: 'https://tsuyosuketeniss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tsuyosuketeniss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaSn41e8Ofnems3wfLWi0K0W5gJul73Mc',
    appId: '1:765408552100:ios:86f246f29fbfb9a5e8b231',
    messagingSenderId: '765408552100',
    projectId: 'tsuyosuketeniss',
    databaseURL: 'https://tsuyosuketeniss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tsuyosuketeniss.appspot.com',
    iosClientId: '765408552100-ftvpccs7tvvh9t1qvvr1aaeljlckus5l.apps.googleusercontent.com',
    iosBundleId: 'com.tsuyosukeTennisAp',
  );
}
